package reality

import (
	"net"
	"strconv"
)

//BaseBUNKER : Where users are
const BaseBUNKER = 0

//BaseSAM : Ground based Anti-Air station
const BaseSAM = 1

//BaseRADAR : Ground based Radar for unit detection
const BaseRADAR = 2

//BaseAIRSTRIP : Used to house and launch aircraft
const BaseAIRSTRIP = 3

//BaseFUELDEPOT : Used to store Fuel to transport to other bases
const BaseFUELDEPOT = 4

//BaseAMMODEPOT : Used to store ammunitions to transport to other bases
const BaseAMMODEPOT = 5

//BaseTRANSDEPOT : Used to store land vehicles for transporting resources and offense
const BaseTRANSDEPOT = 6

//BasePORT : Used to store sea vehicles for transporting resources and offense
const BasePORT = 7

//Building : Contains the information to connect infrastructure to physical computer
type Building interface {
	Name() string
	BaseType() string
	IpAddress() string
	IpPort() int
}

// Base : Generic base type
type Base struct {
	name      string
	baseType  int
	ipAddress string
	ipPort    int
}

// Name : returns the name of the base
func (b Base) Name() string {
	return b.name
}

// BaseType : returns the name of the base
func (b Base) BaseType() string {
	switch b.baseType {
	case 0:
		return "Bunker"
	case 1:
		return "SAM"
	case 2:
		return "RADAR"
	case 3:
		return "Air_Strip"
	case 4:
		return "Fuel_Depot"
	case 5:
		return "Ammo_Depot"
	case 6:
		return "Transport_Depot"
	case 7:
		return "Port"
	default:
	}
	return "unknown"
}

//IPAddress : returns the IP address of the base
func (b Base) IPAddress() string {
	return b.ipAddress
}

//IPPort : returns the IP port of the base main service
func (b Base) IPPort() int {
	return b.ipPort
}

//BaseCreate : creates a base
func BaseCreate(t Team, n string, b int, i string, p int) Base {
	// name comes from random word list
	// ipAddr comes from list generated by initial cidr notation
	// ipPort is generated by initial random list separated by type
	if IPv4Check(i) {
		base := Base{name: n, baseType: b, ipAddress: i, ipPort: p}
		return base
	}
	return Base{}
}

//BaseToString : formats the values of a base in the form of a string
func BaseToString(b Base) string {
	var str = b.name + ": " + "\n\tIP Address: \t" + b.ipAddress + "\n\tIP Port: \t" + strconv.Itoa(b.ipPort)
	return str
}

//IPv4Check : Checks if a string is a valid IPv4 address
func IPv4Check(ipAddress string) bool {
	testInput := net.ParseIP(ipAddress)
	if testInput.To4() == nil {
		// 	fmt.Printf("%v is not a valid IPv4 address\n", testInput)
		return false
	}
	// fmt.Printf("%v is a valid IPv4 address\n", testInput)
	return true
}
